### ISSUE TITLE
Anonymisierte Umfrage mit TAN funktioniert nicht 

### ISSUE THREAD

**Issue by merlincom** [hschottm/survey_ce#19]
[TAN_Mitgliederversammlung mit GV 2020.pdf](https://github.com/hschottm/survey_ce/files/4366124/TAN_Mitgliederversammlung.mit.GV.2020.pdf)
Hallo
Ich habe gerade für unseren Verein eine Umfrage erstellt (als Ersatz für die anstehenden GV)
Das ist der Link: https://www.vbbrb.ch/de/mitgliederve...0-virtuel.html

Was habe ich gemacht?
[1] Umfrage: (X) Anonymisierte Umfrage mit TAN
[2] TAN-Erzeugung für die Umfraage ID x öffnen
[3] TAN-Codes erzeugen
[4] Anzahl der Codes: 40 > Erzeugen
[5] TAN-Codes exportieren

Es wurden folgende Tan-Codes esportiert:
z.B: 123195, 144337, 154395, 171402 etc. sowie die URL's wie https://www.vbbrb.ch/de/mitgliederve...de/903839.html (siehe Anhang)

[6] Aufruf der URL https://www.vbbrb.ch/de/mitgliederve...0-virtuel.html
[7] Eingabe eines unbenutzen TAN-Codes, z.b. 903839
[8] Der eingegebene TAN-Code ist nicht gültig für diese Umfrage. Bitte geben Sie eine gültige TAN ein.

Besten Dank für Unterstützung. Ich weiss nicht mehr weiter.

Gruss von Marcel aus Basel

**Comment by merlincom** [comment]
[TAN_Mitgliederversammlung mit GV 2020.pdf](https://github.com/hschottm/survey_ce/files/4366127/TAN_Mitgliederversammlung.mit.GV.2020.pdf)

**Comment by merlincom** [comment]
Meinen bescheidenenSQL- und PHP-Kenntnissen steckt das Problem in der Datei ContentSurvey.php

`case 'anoncode':
                    $tan = \Input::post('tan');
                    if ((0 == strcmp(\Input::post('FORM_SUBMIT'), 'tl_survey_form')) && (\strlen($tan))) {
                        $result = $this->svy->checkPINTAN($this->objSurvey->id, '', $tan);
                        if (false == $result) {
                            $this->Template->tanMsg = $GLOBALS['TL_LANG']['ERR']['survey_wrong_tan'];
`

**Comment by hschottm** [comment]
Behoben in cc91af10141211495a8cda28a5e48b239d08ead1
Leider wurde der Rückgabewert der Funktion, die die TAN's zur Umfrage heraussucht falsch überprüft. Eine neue Version 3.2.7 wurde für Contao Manager auf Packagist bereit gestellt.

**Comment by merlincom** [comment]
Lieber Helmut
Herzlichen Dank für deine Arbeit und auch deine rasche Reaktion - mit dem Update funktioniert nun alles wunderbar.
Ich benötige solche Umfragen öfter für einen geschlossenen Mitgliederkreis. So wie ich jetzt verstehe, müsste ich wählen
[X] Anonymisierte Umfrage mit TAN
im Mailing aus Contao jeweils dem Nutzer einen Key mitsenden, wofür es keine Standardfunktion gibt
    oder
[X] Personalisierte Umfrage
jedem Mitglied ein Login auf meine Contao-Webseite frei machen, was die Standardfunktionen zulassen.
Ich bevorzuge aber ersteres, wie es in Lime Survey auch möglich ist (E-Mail mit automatischem generiertem individuellen Key). Wird es jemals noch so eine Funktion in Contao geben im Sinne von E-Mail an Gruppe mit jeweils individuellem Key aus dem ce_suryey-key-Modul senden?
