### ISSUE TITLE
table tag  problem im multiplechoise template

### ISSUE THREAD

**Issue by Ma3xl3** [hschottm/survey_ce#5]
Im Template  survey_question_multiplechoice.html5 ist ein Table-Tag-Abschluss vorhanden der nicht an diese Stelle gehört (Zeile 112).

``` HTML
<?php endfor; ?>
	</select>
</div>
<?php endif; ?>
<?php endif; ?>
</table>
````

**Comment by hschottm** [comment]
Fixed in commit 67e9cab
